# Configuration settings

# QID 10919 = KTO nps survey from 27-8-2021
default:
  parse: TRUE
  qid: 10919
  cutoff_date: "2021-08-27 00:00:01"
  writeback: TRUE
  save_location: ""
  
test:
  inherits: default
  save_location: "test_"

# QID 10919 = KTO nps survey from 27-8-2021
nps:
  parse: TRUE
  qid: 10919
  cutoff_date: "2021-08-27 00:00:01"
  writeback: TRUE
  save_location: ""
  
# QID 11850 = profiling survey from XX-XX-2021
profiling:
  parse: TRUE
  qid: 11850
  cutoff_date: "2021-10-31 00:00:01"
  writeback: FALSE
  save_location: ""

# QID 11861 | 11812 = shell churn M&M survey from XX-XX-2021
shell_churn:
  parse: TRUE
  qid: 11861
  cutoff_date: "2021-10-31 00:00:01"
  writeback: FALSE
  save_location: ""  
  
nps_load:
  inherits: nps
  writeback: FALSE

load_all:
  inherits: default
  writeback: FALSE
  cutoff_date: "2020-01-01 00:00:01"
